FROM python:3.8-buster

RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools
RUN python3 -m pip install nvflare==2.4.0

WORKDIR /workspace/

# Copy the current directory contents into the container
COPY requirements.txt /workspace/
# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

ENV PYTHONPATH=$PYTHONPATH:/workspace/app/code/
ENV NVFLARE_POC_WORKSPACE=/workspace/poc-workspace

COPY . /workspace/

CMD ["/bin/bash"]